---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubedoom
  namespace: kubedoom
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: kubedoom
  template:
    metadata:
      labels:
        app: kubedoom
    spec:
      containers:
      - image: storaxdev/kubedoom:0.5.0
        name: kubedoom
        ports:
          - containerPort: 5900
            protocol: TCP
      hostNetwork: true
      serviceAccountName: kubedoom

